switch to https
netmanchris/pyawair pull request #33
Opened 2020-01-31 18:18 UTC by cajaks2

This should 100% be https

2020-01-31 18:40 UTC, netmanchris commented
@cajaks2  Just getting back to this library after some time away and some tests are failing. My guess is that your PR failing test are due to faults in the test and not your code. Looking into fixing test now. 

Will review the PR once I get the tests resolved.

2020-01-31 22:49 UTC, netmanchris requested changes
Cut and paste added an extra s in a couple of places. Please take a quick look and make sure that https:// is valid in all changes, including in the Docstrings.  Other than that, looks good and I was able to get through a Travis run without server-side errors so code is still functional based on tests.

2020-01-31 22:51 UTC, netmanchris commented on pyawair/devices.py
> +    httpss://en.wikipedia.org/wiki/List_of_tz_database_time_zones
Extra "s" in url header

2020-01-31 22:52 UTC, netmanchris commented on pyawair/devices.py
> +    httpss://en.wikipedia.org/wiki/List_of_tz_database_time_zones
Extra "s" in url header

2020-01-31 22:56 UTC, netmanchris commented
@cajaks2  Can you please merge in the test fixes into your PR so that we can get the Travis build to run again? thanks!

2020-02-19 17:29 UTC, cajaks2 commented
Should be good at this point: LED tests also seemed to fail with a 502.  

> On Jan 31, 2020, at 2:56 PM, Christopher Young <notifications@github.com> wrote:
> 
> ﻿
> @cajaks2 Can you please merge in the test fixes into your PR so that we can get the Travis build to run again? thanks!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-02-19 20:55 UTC, merged

2020-02-19 20:56 UTC, netmanchris commented
Talked to Awair and there are some flacky tests due to what's probably an issue on their side. ( 502 points to that being the case ). Tests passed so I'll merge this through and watch in the future to see how things go. Thanks!